/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import mundotravel.CConexion;
/**
 *
 * @author victo
 */
public class RegistroClientes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroClientes
     */
    public RegistroClientes() {
        initComponents();
        initCountryComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenido = new javax.swing.JPanel();
        Imagen = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        FormularioRegistro = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PaisTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        PaisConboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ApellidosTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Contraseñatxt = new javax.swing.JPasswordField();
        DNItxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EmpezarBtn = new javax.swing.JButton();
        codigotxt = new javax.swing.JTextField();
        NumeroCelularTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        panelContenido.setForeground(new java.awt.Color(255, 255, 255));

        Imagen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES_REGISTRO_DE_VUELOS/registro.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout ImagenLayout = new javax.swing.GroupLayout(Imagen);
        Imagen.setLayout(ImagenLayout);
        ImagenLayout.setHorizontalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagenLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        ImagenLayout.setVerticalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagenLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );

        FormularioRegistro.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.CardLayout());
        FormularioRegistro.add(jPanel4, "card2");

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel1.setText("Nombre");

        PaisTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PaisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel2.setText("Apellidos");

        NombreTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel3.setText("DNI");

        EmailTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EmailTxt.setCaretColor(new java.awt.Color(10, 0, 0));
        EmailTxt.setSelectionColor(new java.awt.Color(0, 102, 255));
        EmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTxtActionPerformed(evt);
            }
        });

        PaisConboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PaisConboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisConboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel4.setText("Numero de Celular");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel5.setText("Pais");

        ApellidosTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ApellidosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel6.setText("Contraseña");

        Contraseñatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContraseñatxtMouseClicked(evt);
            }
        });

        DNItxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DNItxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNItxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel7.setText("Email de la Empresa");

        EmpezarBtn.setText("Empezar ya");
        EmpezarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarBtnActionPerformed(evt);
            }
        });

        codigotxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codigotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigotxtActionPerformed(evt);
            }
        });

        NumeroCelularTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NumeroCelularTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCelularTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApellidosTxt)
                    .addComponent(EmpezarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contraseñatxt)
                    .addComponent(DNItxt)
                    .addComponent(EmailTxt)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addGroup(panelContenidoLayout.createSequentialGroup()
                                .addComponent(codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumeroCelularTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContenidoLayout.createSequentialGroup()
                            .addComponent(PaisConboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PaisTxt))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormularioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContenidoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NombreTxt, jLabel1, jLabel2, jLabel3});

        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(FormularioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(DNItxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ApellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaisConboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroCelularTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseñatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmpezarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        panelContenidoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ApellidosTxt, Contraseñatxt, EmailTxt, NombreTxt, PaisTxt});

        panelContenidoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {NumeroCelularTxt, codigotxt});

        PaisTxt.getAccessibleContext().setAccessibleParent(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initCountryComboBox() {
        DefaultComboBoxModel<String> countryModel = new DefaultComboBoxModel<>();
        countryModel.addElement("Seleccione un país"); // Opción predeterminada
        countryModel.addElement("Argentina (+54)");
        countryModel.addElement("Bolivia (+591)");
        countryModel.addElement("Brasil (+55)");
        countryModel.addElement("Chile (+56)");
        countryModel.addElement("Colombia (+57)");
        countryModel.addElement("Ecuador (+593)");
        countryModel.addElement("Perú (+51)");
        countryModel.addElement("Uruguay (+598)");
        countryModel.addElement("Venezuela (+58)");

        PaisConboBox.setModel(countryModel);

        PaisConboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedCountry = PaisConboBox.getSelectedItem().toString();
                    switch (selectedCountry) {
                        case "Argentina (+54)":
                            codigotxt.setText("+54");
                            break;
                        case "Bolivia (+591)":
                            codigotxt.setText("+591");
                            break;
                        case "Perú (+51)":
                            codigotxt.setText("+51");
                            break;
                        // Agrega más casos para otros países y códigos postales aquí
                        default:
                            codigotxt.setText(""); // Borra el código postal si no se selecciona un país válido
                            break;
                    }
                }
            }
        });
    }
    
    
    private void PaisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void EmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTxtActionPerformed

    private void ApellidosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosTxtActionPerformed

    private void DNItxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNItxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNItxtActionPerformed

    private void EmpezarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarBtnActionPerformed
        // Obtener los datos ingresados en los campos de texto
        String nombre = NombreTxt.getText();
        String apellidos = ApellidosTxt.getText();
        String dni = DNItxt.getText();
        String email = EmailTxt.getText();
        String pais = PaisTxt.getText();
        String numeroCelular = NumeroCelularTxt.getText();
        String contrasena = new String(Contraseñatxt.getPassword()); // Contraseña como texto

        // Validar que los campos no estén vacíos (puedes agregar más validaciones según tus necesidades)
        if (nombre.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || email.isEmpty() || pais.isEmpty() || numeroCelular.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

            // Guardar los datos en la base de datos
        try {
            CConexion conexionDB = new CConexion();
            Connection conexion = conexionDB.establecerConnection();

            // Verifica si la conexión se estableció correctamente
            if (conexion != null) {
                // Crear la consulta SQL para insertar un nuevo cliente en la tabla
                String insercionSQL = "INSERT INTO Cliente (Nombre, Apellido, Dni, Numero_Cel, Correo) VALUES (?, ?, ?, ?, ?)";

                // Crear una sentencia preparada
                PreparedStatement pstmt = conexion.prepareStatement(insercionSQL);
                pstmt.setString(1, nombre);
                pstmt.setString(2, apellidos);
                pstmt.setString(3, dni);
                pstmt.setString(4, numeroCelular);
                pstmt.setString(5, email);
                // Ejecutar la consulta para insertar los datos
                int filasInsertadas = pstmt.executeUpdate();

                // Cerrar la conexión
                pstmt.close();

                if (filasInsertadas > 0) {
                    JOptionPane.showMessageDialog(this, "Los datos se guardaron correctamente.", "Guardado exitoso", JOptionPane.INFORMATION_MESSAGE);
                    // Reiniciar o cerrar el formulario aquí, según tus necesidades
                    // Cierra la ventana actual
                    dispose();

                    // Abre la ventana de inicio de sesión (Login)
                    Login loginForm = new Login();
                    loginForm.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudieron guardar los datos.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo establecer la conexión a la base de datos.", "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_EmpezarBtnActionPerformed

    private void PaisConboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisConboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisConboBoxActionPerformed

    private void codigotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigotxtActionPerformed

    private void NumeroCelularTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCelularTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCelularTxtActionPerformed

    private void ContraseñatxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñatxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñatxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosTxt;
    private javax.swing.JPasswordField Contraseñatxt;
    private javax.swing.JTextField DNItxt;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JButton EmpezarBtn;
    private javax.swing.JPanel FormularioRegistro;
    private javax.swing.JPanel Imagen;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField NumeroCelularTxt;
    private javax.swing.JComboBox<String> PaisConboBox;
    private javax.swing.JTextField PaisTxt;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
