/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import java.awt.Panel;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import java.awt.Insets;
import javax.swing.border.Border;

/**
 *
 * @author victo
 */
public class vista_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form vista_Inicio
     */
    public vista_Inicio() {
        initComponents();
        // Agrega un borde compuesto al jPanel1
        jPanel1.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createBevelBorder(BevelBorder.RAISED), // Borde resaltado
        BorderFactory.createBevelBorder(BevelBorder.LOWERED) // Borde en relieve
         ));
        // Crea un borde con esquinas redondeadas
        Border roundedBorder = BorderFactory.createEmptyBorder(10, 10, 10, 10);
        Menu.setBorder(new CompoundBorder(
            BorderFactory.createBevelBorder(BevelBorder.RAISED), // Borde resaltado
            roundedBorder // Borde con esquinas redondeadas
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Baner = new javax.swing.JPanel();
        AerolineasLabel = new javax.swing.JLabel();
        InicioLabel = new javax.swing.JLabel();
        PaquetesLabel = new javax.swing.JLabel();
        ViajesLabel = new javax.swing.JLabel();
        ItenerariosLabel = new javax.swing.JLabel();
        CantactosLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FacturasLabel = new javax.swing.JLabel();
        InformesLabel = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Menu = new javax.swing.JPanel();
        tablePrincipal = new javax.swing.JTabbedPane();
        Vuelos = new javax.swing.JScrollPane();
        panelContenido = new javax.swing.JPanel();
        PanelReserva = new javax.swing.JTabbedPane();
        SoloIda = new javax.swing.JScrollPane();
        PanelSoloIda = new javax.swing.JPanel();
        RegresoIcon = new javax.swing.JLabel();
        CambiarIcon = new javax.swing.JLabel();
        OrigenIcon = new javax.swing.JLabel();
        Origentxt = new javax.swing.JTextField();
        AddViajeroicon = new javax.swing.JLabel();
        Costo = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        fechaIcon = new javax.swing.JLabel();
        BuscarVuelobtn = new javax.swing.JButton();
        vuelosDirectostxt = new javax.swing.JCheckBox();
        Addviajerotxt = new javax.swing.JTextField();
        Retornotxt = new javax.swing.JTextField();
        fechaIdatxt = new javax.swing.JTextField();
        IdayVuelta = new javax.swing.JScrollPane();
        PanelSoloIda1 = new javax.swing.JPanel();
        RegresoIcon1 = new javax.swing.JLabel();
        CambiarIcon1 = new javax.swing.JLabel();
        OrigenIcon1 = new javax.swing.JLabel();
        Origentxt1 = new javax.swing.JTextField();
        AddViajeroicon1 = new javax.swing.JLabel();
        Costo1 = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        fechaIcon1 = new javax.swing.JLabel();
        BuscarVuelobtn1 = new javax.swing.JButton();
        vuelosDirectostxt1 = new javax.swing.JCheckBox();
        Addviajerotxt1 = new javax.swing.JTextField();
        Retornotxt1 = new javax.swing.JTextField();
        vueltatxt = new javax.swing.JTextField();
        fechaIcon2 = new javax.swing.JLabel();
        fechaIdatxt2 = new javax.swing.JTextField();
        MultiplesCiudades = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        OrigenLabel9 = new javax.swing.JLabel();
        OrigenLabel25 = new javax.swing.JLabel();
        OrigenLabel26 = new javax.swing.JLabel();
        Origentxt20 = new javax.swing.JTextField();
        OrigenLabel27 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        OrigenLabel28 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jCheckBox8 = new javax.swing.JCheckBox();
        Origentxt21 = new javax.swing.JTextField();
        Origentxt22 = new javax.swing.JTextField();
        Origentxt23 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Origentxt24 = new javax.swing.JTextField();
        OrigenLabel29 = new javax.swing.JLabel();
        OrigenLabel30 = new javax.swing.JLabel();
        OrigenLabel10 = new javax.swing.JLabel();
        Origentxt25 = new javax.swing.JTextField();
        OrigenLabel31 = new javax.swing.JLabel();
        Origentxt26 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        Alojamientos = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        OrigenLabel15 = new javax.swing.JLabel();
        Origentxt12 = new javax.swing.JTextField();
        OrigenLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        OrigenLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        Origentxt13 = new javax.swing.JTextField();
        Origentxt14 = new javax.swing.JTextField();
        Trenes = new javax.swing.JScrollPane();
        Coches = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Baner.setBackground(new java.awt.Color(255, 255, 255));

        AerolineasLabel.setText("Aerolineas");

        InicioLabel.setText("Inicio");

        PaquetesLabel.setText("Paquetes");

        ViajesLabel.setText("Viajes");

        ItenerariosLabel.setText("Itenerarios");

        CantactosLabel.setText("Contactos");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES_REGISTRO_DE_VUELOS/logo.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        FacturasLabel.setText("Facturas");

        InformesLabel.setText("Informes");

        javax.swing.GroupLayout BanerLayout = new javax.swing.GroupLayout(Baner);
        Baner.setLayout(BanerLayout);
        BanerLayout.setHorizontalGroup(
            BanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304)
                .addComponent(InicioLabel)
                .addGap(40, 40, 40)
                .addComponent(PaquetesLabel)
                .addGap(40, 40, 40)
                .addComponent(ViajesLabel)
                .addGap(40, 40, 40)
                .addComponent(ItenerariosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CantactosLabel)
                .addGap(40, 40, 40)
                .addComponent(AerolineasLabel)
                .addGap(40, 40, 40)
                .addComponent(FacturasLabel)
                .addGap(40, 40, 40)
                .addComponent(InformesLabel)
                .addGap(40, 40, 40))
        );
        BanerLayout.setVerticalGroup(
            BanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BanerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BanerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaquetesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViajesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItenerariosLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CantactosLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FacturasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AerolineasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InicioLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(BanerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(255, 204, 204));
        Menu.setDoubleBuffered(false);

        tablePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));

        PanelReserva.setDoubleBuffered(true);
        PanelReserva.setFocusCycleRoot(true);
        PanelReserva.setFocusTraversalPolicyProvider(true);
        PanelReserva.setInheritsPopupMenu(true);
        PanelReserva.setRequestFocusEnabled(false);
        PanelReserva.setVerifyInputWhenFocusTarget(false);

        SoloIda.setBackground(new java.awt.Color(255, 255, 255));
        SoloIda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PanelSoloIda.setBackground(new java.awt.Color(255, 255, 255));

        RegresoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_land_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        CambiarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sync_alt_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_takeoff_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Origentxt.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt.setText("De");
        Origentxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrigentxtActionPerformed(evt);
            }
        });

        AddViajeroicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/person_add_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Costo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Costo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoActionPerformed(evt);
            }
        });

        fechaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar_today_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        fechaIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaIconMouseClicked(evt);
            }
        });

        BuscarVuelobtn.setBackground(new java.awt.Color(0, 102, 255));
        BuscarVuelobtn.setForeground(new java.awt.Color(255, 255, 255));
        BuscarVuelobtn.setText("Buscar  Vuelos");

        vuelosDirectostxt.setText("Solo vuelos Directos");

        Addviajerotxt.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Addviajerotxt.setForeground(new java.awt.Color(153, 153, 153));
        Addviajerotxt.setText("Añadir Viajero");
        Addviajerotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddviajerotxtActionPerformed(evt);
            }
        });

        Retornotxt.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Retornotxt.setForeground(new java.awt.Color(153, 153, 153));
        Retornotxt.setText("A");
        Retornotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornotxtActionPerformed(evt);
            }
        });

        fechaIdatxt.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        fechaIdatxt.setForeground(new java.awt.Color(153, 153, 153));
        fechaIdatxt.setText("Ida");
        fechaIdatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaIdatxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSoloIdaLayout = new javax.swing.GroupLayout(PanelSoloIda);
        PanelSoloIda.setLayout(PanelSoloIdaLayout);
        PanelSoloIdaLayout.setHorizontalGroup(
            PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                        .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7)
                            .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaIcon)
                                    .addComponent(OrigenIcon))
                                .addGap(18, 18, 18)
                                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                                        .addComponent(Origentxt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(CambiarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RegresoIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Retornotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                                        .addComponent(fechaIdatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Costo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 40, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                        .addComponent(AddViajeroicon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Addviajerotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vuelosDirectostxt)
                        .addGap(26, 26, 26)
                        .addComponent(BuscarVuelobtn)
                        .addGap(42, 42, 42))))
        );
        PanelSoloIdaLayout.setVerticalGroup(
            PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegresoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambiarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Retornotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fechaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaIdatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Costo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vuelosDirectostxt)
                                    .addComponent(BuscarVuelobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelSoloIdaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelSoloIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Addviajerotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddViajeroicon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        SoloIda.setViewportView(PanelSoloIda);

        PanelReserva.addTab("Solo de ida", SoloIda);

        IdayVuelta.setBorder(null);

        PanelSoloIda1.setBackground(new java.awt.Color(255, 255, 255));

        RegresoIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_land_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        CambiarIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sync_alt_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_takeoff_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Origentxt1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt1.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt1.setText("De");
        Origentxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt1ActionPerformed(evt);
            }
        });

        AddViajeroicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/person_add_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Costo1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Costo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fechaIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar_today_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        BuscarVuelobtn1.setBackground(new java.awt.Color(0, 102, 255));
        BuscarVuelobtn1.setForeground(new java.awt.Color(255, 255, 255));
        BuscarVuelobtn1.setText("Buscar  Vuelos");

        vuelosDirectostxt1.setText("Solo vuelos Directos");

        Addviajerotxt1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Addviajerotxt1.setForeground(new java.awt.Color(153, 153, 153));
        Addviajerotxt1.setText("Añadir Viajero");
        Addviajerotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addviajerotxt1ActionPerformed(evt);
            }
        });

        Retornotxt1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Retornotxt1.setForeground(new java.awt.Color(153, 153, 153));
        Retornotxt1.setText("A");
        Retornotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retornotxt1ActionPerformed(evt);
            }
        });

        vueltatxt.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        vueltatxt.setForeground(new java.awt.Color(153, 153, 153));
        vueltatxt.setText("vuelta");
        vueltatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueltatxtActionPerformed(evt);
            }
        });

        fechaIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar_today_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        fechaIdatxt2.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        fechaIdatxt2.setForeground(new java.awt.Color(153, 153, 153));
        fechaIdatxt2.setText("Ida");
        fechaIdatxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaIdatxt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSoloIda1Layout = new javax.swing.GroupLayout(PanelSoloIda1);
        PanelSoloIda1.setLayout(PanelSoloIda1Layout);
        PanelSoloIda1Layout.setHorizontalGroup(
            PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                        .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9)
                            .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaIcon1)
                                    .addComponent(OrigenIcon1))
                                .addGap(18, 18, 18)
                                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                                        .addComponent(Origentxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(CambiarIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RegresoIcon1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Retornotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                                        .addComponent(fechaIdatxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fechaIcon2)
                                        .addGap(18, 18, 18)
                                        .addComponent(vueltatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Costo1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 40, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                        .addComponent(AddViajeroicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Addviajerotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vuelosDirectostxt1)
                        .addGap(26, 26, 26)
                        .addComponent(BuscarVuelobtn1)
                        .addGap(42, 42, 42))))
        );
        PanelSoloIda1Layout.setVerticalGroup(
            PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegresoIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambiarIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Retornotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fechaIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vueltatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Costo1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fechaIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaIdatxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vuelosDirectostxt1)
                                    .addComponent(BuscarVuelobtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelSoloIda1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelSoloIda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Addviajerotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddViajeroicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        IdayVuelta.setViewportView(PanelSoloIda1);

        PanelReserva.addTab("Ida y vuelta", IdayVuelta);

        MultiplesCiudades.setBorder(null);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        OrigenLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_land_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sync_alt_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_takeoff_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Origentxt20.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt20.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt20.setText("De");
        Origentxt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt20ActionPerformed(evt);
            }
        });

        OrigenLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/person_add_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar_today_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        jButton7.setBackground(new java.awt.Color(0, 102, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Buscar  Vuelos");

        jCheckBox8.setText("Solo vuelos Directos");

        Origentxt21.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt21.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt21.setText("Añadir Viajero");
        Origentxt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt21ActionPerformed(evt);
            }
        });

        Origentxt22.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt22.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt22.setText("A");
        Origentxt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt22ActionPerformed(evt);
            }
        });

        Origentxt23.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt23.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt23.setText("Ida");
        Origentxt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt23ActionPerformed(evt);
            }
        });

        jTextField2.setText("X");
        jTextField2.setBorder(null);

        Origentxt24.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt24.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt24.setText("De");
        Origentxt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt24ActionPerformed(evt);
            }
        });

        OrigenLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_takeoff_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sync_alt_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_land_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Origentxt25.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt25.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt25.setText("A");
        Origentxt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt25ActionPerformed(evt);
            }
        });

        OrigenLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar_today_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Origentxt26.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt26.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt26.setText("Ida");
        Origentxt26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt26ActionPerformed(evt);
            }
        });

        jTextField3.setText("X");
        jTextField3.setBorder(null);

        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jButton1.setText("Añadir Vuelo");

        jComboBox3.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OrigenLabel26)
                            .addComponent(OrigenLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(Origentxt24, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrigenLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(OrigenLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Origentxt25, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrigenLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Origentxt26, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(Origentxt20, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrigenLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrigenLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Origentxt22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OrigenLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Origentxt23, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(109, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(OrigenLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Origentxt21, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(jCheckBox8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton7)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrigenLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Origentxt23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OrigenLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Origentxt24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrigenLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Origentxt26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrigenLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Origentxt21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        MultiplesCiudades.setViewportView(jPanel14);

        PanelReserva.addTab("Múltiples ciudades", MultiplesCiudades);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(PanelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(PanelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        Vuelos.setViewportView(panelContenido);

        tablePrincipal.addTab("Vuelos", Vuelos);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        OrigenLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flight_takeoff_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        Origentxt12.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt12.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt12.setText("Ingresa el lugar");
        Origentxt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt12ActionPerformed(evt);
            }
        });

        OrigenLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/person_add_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        OrigenLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar_today_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        jButton4.setText("Buscar  Vuelos");

        jCheckBox5.setText("Solo apartamentos");

        Origentxt13.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt13.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt13.setText("Selecciona Fecha");
        Origentxt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt13ActionPerformed(evt);
            }
        });

        Origentxt14.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        Origentxt14.setForeground(new java.awt.Color(153, 153, 153));
        Origentxt14.setText("Añadir viajero");
        Origentxt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origentxt14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(479, Short.MAX_VALUE)
                .addComponent(OrigenLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Origentxt13, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(OrigenLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox5)
                                .addGap(28, 28, 28)
                                .addComponent(jButton4)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Origentxt14, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(OrigenLabel15)
                    .addContainerGap(842, Short.MAX_VALUE)))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(Origentxt12, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(538, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OrigenLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrigenLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Origentxt14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jCheckBox5))
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(OrigenLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(491, Short.MAX_VALUE)))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(Origentxt12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(491, Short.MAX_VALUE)))
        );

        jScrollPane4.setViewportView(jPanel11);

        Alojamientos.setViewportView(jScrollPane4);

        tablePrincipal.addTab("Alojamientos", Alojamientos);
        tablePrincipal.addTab("Trenes", Trenes);

        Coches.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setVerifyInputWhenFocusTarget(false);
        jTabbedPane2.addTab("tab1", jScrollPane6);

        jScrollPane7.setBorder(null);
        jTabbedPane2.addTab("tab1", jScrollPane7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        Coches.setViewportView(jPanel6);

        tablePrincipal.addTab("Coches", Coches);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(tablePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tablePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setText("¿Viajas por trabajo?, ¡Vamos allá!");

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setText("Hola vienvenido a mundo travel , Manuel");

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(418, 418, 418))))
            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                    .addContainerGap(521, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(389, 389, 389)))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenidoLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel11)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Baner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Baner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Origentxt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt14ActionPerformed

    private void Origentxt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt13ActionPerformed

    private void Origentxt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt12ActionPerformed

    private void Origentxt26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt26ActionPerformed

    private void Origentxt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt25ActionPerformed

    private void Origentxt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt24ActionPerformed

    private void Origentxt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt23ActionPerformed

    private void Origentxt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt22ActionPerformed

    private void Origentxt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt21ActionPerformed

    private void Origentxt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt20ActionPerformed

    private void fechaIdatxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaIdatxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIdatxt2ActionPerformed

    private void vueltatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueltatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vueltatxtActionPerformed

    private void Retornotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retornotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Retornotxt1ActionPerformed

    private void Addviajerotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addviajerotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Addviajerotxt1ActionPerformed

    private void Origentxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origentxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Origentxt1ActionPerformed

    private void fechaIdatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaIdatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIdatxtActionPerformed

    private void RetornotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetornotxtActionPerformed

    private void AddviajerotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddviajerotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddviajerotxtActionPerformed

    private void fechaIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIconMouseClicked

    private void CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoActionPerformed

    private void OrigentxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrigentxtActionPerformed

    }//GEN-LAST:event_OrigentxtActionPerformed
    private void OrigentxtMouseClicked(java.awt.event.MouseEvent evt) {                                          
        Origentxt.setText(""); // Limpia el contenido del campo al hacer clic
    }
    private void fechaIdatxtMouseClicked(java.awt.event.MouseEvent evt) {                                          
    fechaIdatxt.setText(""); // Limpia el contenido del campo al hacer clic
    }

    private void RetornotxtMouseClicked(java.awt.event.MouseEvent evt) {                                           
        Retornotxt.setText(""); // Limpia el contenido del campo al hacer clic
    }

    private void AddviajerotxtMouseClicked(java.awt.event.MouseEvent evt) {                                              
        Addviajerotxt.setText(""); // Limpia el contenido del campo al hacer clic
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddViajeroicon;
    private javax.swing.JLabel AddViajeroicon1;
    private javax.swing.JTextField Addviajerotxt;
    private javax.swing.JTextField Addviajerotxt1;
    private javax.swing.JLabel AerolineasLabel;
    private javax.swing.JScrollPane Alojamientos;
    private javax.swing.JPanel Baner;
    private javax.swing.JButton BuscarVuelobtn;
    private javax.swing.JButton BuscarVuelobtn1;
    private javax.swing.JLabel CambiarIcon;
    private javax.swing.JLabel CambiarIcon1;
    private javax.swing.JLabel CantactosLabel;
    private javax.swing.JScrollPane Coches;
    private javax.swing.JPanel Contenido;
    private javax.swing.JComboBox<String> Costo;
    private javax.swing.JComboBox<String> Costo1;
    private javax.swing.JLabel FacturasLabel;
    private javax.swing.JScrollPane IdayVuelta;
    private javax.swing.JLabel InformesLabel;
    private javax.swing.JLabel InicioLabel;
    private javax.swing.JLabel ItenerariosLabel;
    private javax.swing.JPanel Menu;
    private javax.swing.JScrollPane MultiplesCiudades;
    private javax.swing.JLabel OrigenIcon;
    private javax.swing.JLabel OrigenIcon1;
    private javax.swing.JLabel OrigenLabel10;
    private javax.swing.JLabel OrigenLabel15;
    private javax.swing.JLabel OrigenLabel16;
    private javax.swing.JLabel OrigenLabel17;
    private javax.swing.JLabel OrigenLabel25;
    private javax.swing.JLabel OrigenLabel26;
    private javax.swing.JLabel OrigenLabel27;
    private javax.swing.JLabel OrigenLabel28;
    private javax.swing.JLabel OrigenLabel29;
    private javax.swing.JLabel OrigenLabel30;
    private javax.swing.JLabel OrigenLabel31;
    private javax.swing.JLabel OrigenLabel9;
    private javax.swing.JTextField Origentxt;
    private javax.swing.JTextField Origentxt1;
    private javax.swing.JTextField Origentxt12;
    private javax.swing.JTextField Origentxt13;
    private javax.swing.JTextField Origentxt14;
    private javax.swing.JTextField Origentxt20;
    private javax.swing.JTextField Origentxt21;
    private javax.swing.JTextField Origentxt22;
    private javax.swing.JTextField Origentxt23;
    private javax.swing.JTextField Origentxt24;
    private javax.swing.JTextField Origentxt25;
    private javax.swing.JTextField Origentxt26;
    private javax.swing.JTabbedPane PanelReserva;
    private javax.swing.JPanel PanelSoloIda;
    private javax.swing.JPanel PanelSoloIda1;
    private javax.swing.JLabel PaquetesLabel;
    private javax.swing.JLabel RegresoIcon;
    private javax.swing.JLabel RegresoIcon1;
    private javax.swing.JTextField Retornotxt;
    private javax.swing.JTextField Retornotxt1;
    private javax.swing.JScrollPane SoloIda;
    private javax.swing.JScrollPane Trenes;
    private javax.swing.JLabel ViajesLabel;
    private javax.swing.JScrollPane Vuelos;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel fechaIcon;
    private javax.swing.JLabel fechaIcon1;
    private javax.swing.JLabel fechaIcon2;
    private javax.swing.JTextField fechaIdatxt;
    private javax.swing.JTextField fechaIdatxt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JTabbedPane tablePrincipal;
    private javax.swing.JCheckBox vuelosDirectostxt;
    private javax.swing.JCheckBox vuelosDirectostxt1;
    private javax.swing.JTextField vueltatxt;
    // End of variables declaration//GEN-END:variables
}
